### ISSUE TITLE
how to encode barcode in stereo-seq

### ISSUE THREAD

**Issue by Secretloong** [BGIResearch/ST_Barcode_Map#2]
I only found a `'bpMatrix 1` in `*.barcodeToPos.h5` file, which was encoded by 15 digits. Could I only translate these codes to barcode sequences with their coordinates, but not use the pairwise reads files?

**Comment by liuxingnancy** [comment]
Yes, you can use the mask format transfer function of ST_BarcodeMap to meet your requirement. Just run the command line as shown below. And make sure the suffix of the output file is `.txt`.
```
ST_BarcodeMap-0.0.1 --in mask.h5 --out mask.txt --action 3
```
The output file "mask.txt" contains barcode sequences in  A, T, C, and G bases, along with their corresponding coordinates. Each line of the file contains a record in the following format: barcode, x, y.

**Comment by Secretloong** [comment]
thanks, it works
